import 'key_model.dart';

/// Generates the `LocalinoKeys` Dart source from parsed [keys].
///
/// [keys] are expected pre-sorted (parser sorts alphabetically) for stable
/// diffs. Output is `dart analyze`-clean; runtime const values are the original
/// JSON keys verbatim.
String generateLocalinoKeys(List<LocalinoKey> keys) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by localino_builder — do not edit by hand.')
    ..writeln('// ignore_for_file: constant_identifier_names, '
        'lines_longer_than_80_chars')
    ..writeln()
    ..writeln('abstract final class LocalinoKeys {');

  for (var i = 0; i < keys.length; i++) {
    if (i > 0) {
      buffer.writeln();
    }
    _writeKey(buffer, keys[i]);
  }

  buffer.writeln('}');
  return buffer.toString();
}

void _writeKey(StringBuffer buffer, LocalinoKey key) {
  for (final line in _docLines(key)) {
    buffer.writeln('  /// $line');
  }
  buffer.writeln("  static const ${key.dartName} = '${key.jsonKey}';");
}

List<String> _docLines(LocalinoKey key) {
  final lines = <String>[];

  switch (key.kind) {
    case LocalinoKeyKind.string:
    case LocalinoKeyKind.format:
      if (key.preview.isNotEmpty) {
        lines.add(key.preview);
      }
    case LocalinoKeyKind.map:
      lines.add('(map)');
    case LocalinoKeyKind.list:
      lines.add('(list)');
  }

  if (key.kind == LocalinoKeyKind.format && key.params.isNotEmpty) {
    lines.add('params: ${key.params.join(', ')}');
  }

  if (key.missingLocales.isNotEmpty) {
    lines.add('⚠ missing in: ${key.missingLocales.join(', ')}');
  }

  // Guarantee at least one doc line so every const is documented.
  if (lines.isEmpty) {
    lines.add(key.jsonKey);
  }

  return lines;
}
