part of flutter_control;

/// A utility class for generating unique and random string identifiers.
class UnitId {
  const UnitId._();

  static const az = 'abcdefghijklmnopqrstuvwxyz';
  static const aZ = 'aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ';
  static const azn = 'abcdefghijklmnopqrstuvwxyz0123456789';
  static const aZn =
      'aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ0123456789';
  static const hex = '0123456789ABCDEF';

  /// The default character set used for ID generation.
  static String units = aZn;

  /// A random ID specific to this app instance, used to ensure uniqueness across sessions.
  static String instanceId = randomId(length: 4, sequence: aZn);

  /// A counter that increments for each ID generated within the current app instance.
  static int instanceCounter = 0;

  /// The seed for the random number generator, initialized with the current timestamp.
  static int seed = DateTime.timestamp().microsecondsSinceEpoch;

  /// An optional callback that is triggered whenever a new ID is generated by [nextId].
  static VoidCallback? onChanged;

  /// Cycles through a given [sequence] to build a string based on an [index].
  /// This creates a base-N representation of the index, where N is the length of the sequence.
  ///
  /// For example, with the sequence `abc`:
  /// 0 -> a
  /// 1 -> b
  /// 2 -> c
  /// 3 -> aa
  /// 4 -> ab
  static String cycleId(int index, String sequence) {
    if (index > sequence.length - 1) {
      final count = sequence.length;
      final num = index ~/ count;

      return cycleId(num - 1, sequence) +
          cycleId(index - count * num, sequence);
    }

    return sequence[index];
  }

  /// Returns a cyclical ID using the [az] character set.
  ///
  /// [digitOffset] can be used to ensure the resulting string has a minimum length.
  static String charId(int index, {int digitOffset = 0}) =>
      cycleId(index + _digitCycleOffset(digitOffset, az.length), az);

  /// Generates a globally unique ID based on the current timestamp, instance ID, and an incrementing counter.
  ///
  /// This is the recommended method for generating IDs for objects that need to be unique across app sessions.
  static String nextId() {
    final stamp = DateTime.now().toUtc().microsecondsSinceEpoch;

    final id = '${cycleId(stamp, units)}_${instanceId}_${++instanceCounter}';

    onChanged?.call();

    return id;
  }

  /// Generates a random string of a given [length] from a [sequence] of characters.
  static String randomId({int length = 8, String sequence = az}) {
    return randomFromSequence(length, sequence);
  }

  /// Generates a random string by picking characters from a [sequence].
  static String randomFromSequence(int length, String sequence) {
    final output = StringBuffer();

    final rnd = math.Random(seed);

    for (int i = 0; i < length; i++) {
      output.write(sequence[rnd.nextInt(sequence.length)]);
    }

    return output.toString();
  }

  /// Returns an offset for a given number of digits and sequence count,
  /// used for padding in [charId].
  static int _digitCycleOffset(int digits, int count) {
    if (digits < 2) {
      return 0;
    }

    if (digits < 3) {
      return count;
    }

    int max = 0;
    for (int i = 1; i < digits; i++) {
      max += math.pow(count, i) as int;
    }

    return max;
  }
}
