name: flutter_control
description: Flutter Control is complex library to maintain App and State management, Dependency Injection, Navigation with Routing, Localization and more..
version: 0.98.85+2

homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0
  test_coverage: 0.4.3
  pedantic: ^1.9.0

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: ^0.5.10

flutter:

