name: flutter_control
description: Flutter Control is complex library to maintain App and State management, Dependency Injection, Navigation with Routing, Localization and more..
repository: https://github.com/romanbase/flutter_control
version: 4.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=1.3.2+1 <2.0.0"

  # https://pub.dev/packages/control_config
  control_config: ">=1.3.3 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.2
  pedantic: ^1.11.1