name: flutter_control
description: Flutter Control is complex library to maintain App and State management, Dependency Injection, Navigation with Routing, Localization and more..
version: 2.6.0-beta1

homepage: https://github.com/romanbase/flutter_control

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=0.9.2 <1.0.0"

  # https://pub.dev/packages/control_config
  control_config: ">=0.9.0 <1.0.0"

  # https://pub.dev/packages/localino
  localino: ">=0.9.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  pedantic: ^1.11.1

