name: flutter_control
description: Flutter Control is complex library to maintain App and State management, Dependency Injection, Navigation with Routing, Localization and more..
version: 3.0.3-beta.6

homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/control_core
  control_core: ">=1.0.0 <2.0.0"

  # https://pub.dev/packages/control_config
  control_config: ">=1.0.0 <2.0.0"

  # https://pub.dev/packages/localino
  localino: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.2
  pedantic: ^1.11.1