name: flutter_control
description: Flutter Control is complex library to maintain App and State management, Dependency Injection, Navigation with Routing, Localization and more..
version: 2.5.0-beta4

homepage: https://github.com/romanbase/flutter_control

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  control_core:
    path: ./modules/control_core

  control_config:
    path: ./modules/control_config

  localino:
    path: ./modules/localino

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  pedantic: ^1.11.1

