/// The official `localino` package implementation for connecting to the Localino REST API.
/// Provides Over-The-Air (OTA) updates for translations.
library localino_live;

import 'dart:convert';
import 'dart:io';

import 'package:control_core/core.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:localino/localino.dart';
import 'package:path_provider/path_provider.dart';

part 'src/api.dart';

part 'src/local_repo.dart';

part 'src/remote_repo.dart';

/// Provides factory methods to configure and initialize `localino` with remote capabilities.
class LocalinoLive {
  LocalinoLive._();

  /// Creates an instance of the [_LocalinoLiveApi] which implements [LocalinoRemoteApi].
  static LocalinoRemoteApi instance(LocalinoRemoteOptions options) =>
      _LocalinoLiveApi(options);

  /// Creates an instance of [LocalinoRemoteRepo] for making API calls to the Localino backend.
  static LocalinoRemoteRepo repo(String token, [http.Client? client]) =>
      LocalinoRemoteRepo._(token, client);

  /// Creates an instance of [LocalinoLocalRepo] for caching translations on the device.
  static LocalinoLocalRepo cache() => LocalinoLocalRepo._();

  static InitFactory<LocalinoRemoteApi> get _remote =>
      (args) => instance(Parse.getArg<LocalinoRemoteOptions>(args)!);

  /// A map of factory initializers for dependency injection, used by the `Control` framework.
  static Map<Type, InitFactory> get initializers => {
        LocalinoRemoteApi: _remote,
      };

  /// A convenience method to create [LocalinoOptions] pre-configured for `localino_live`.
  ///
  /// [path] Path to the asset setup file, typically generated by `localino_builder`.
  /// [setup] A manual [LocalinoSetup] object. If provided, `path` is ignored.
  /// [remoteSync] If `true`, enables automatic synchronization of translations on locale changes.
  static LocalinoOptions options({
    String path = 'assets/localization/setup.json',
    LocalinoSetup? setup,
    bool remoteSync = false,
  }) =>
      LocalinoOptions(
        path: path,
        setup: setup,
        remote: _remote,
        remoteSync: remoteSync,
      );
}
