name: control_core
description: Control Core is base library for flutter_control and other control modules.
version: 0.9.4

homepage: https://github.com/romanbase/flutter_control

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter