name: control_core
description: Control Core is direct Service Locator and Observable Handler. Also comes with multiple utilities.
version: 1.1.0

homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter