name: control_core
description: Control Core is direct Service Locator and Observable Handler. Also comes with multiple utilities.
repository: https://github.com/romanbase/flutter_control
version: 1.3.1+1

homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0