name: control_core
description: Core of flutter_control
version: 0.9.0

homepage: https://github.com/romanbase/flutter_control

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter