name: control_macros
description: "A new Flutter project."
version: 0.5.0

homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  control_core: ^1.2.2+1

  # https://pub.dev/packages/macros
  macros: ^0.1.2-main.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0