import 'dart:io';

import 'package:localino_builder/src/key_generator.dart';
import 'package:localino_builder/src/key_model.dart';
import 'package:test/test.dart';

void main() {
  const keys = [
    LocalinoKey(
      jsonKey: 'action_add',
      dartName: 'action_add',
      kind: LocalinoKeyKind.string,
      preview: 'Add',
    ),
    LocalinoKey(
      jsonKey: 'action_delete_locale',
      dartName: 'action_delete_locale',
      kind: LocalinoKeyKind.string,
      preview: 'Delete locale',
      missingLocales: ['cs_CZ'],
    ),
    LocalinoKey(
      jsonKey: 'menu_tabs',
      dartName: 'menu_tabs',
      kind: LocalinoKeyKind.list,
    ),
    LocalinoKey(
      jsonKey: 'onboard_card_1',
      dartName: 'onboard_card_1',
      kind: LocalinoKeyKind.map,
    ),
    LocalinoKey(
      jsonKey: 'version',
      dartName: 'version',
      kind: LocalinoKeyKind.format,
      params: ['version', 'number'],
      preview: 'Version: {version} ({number})',
    ),
  ];

  test('golden output is exact and stable', () {
    const expected = '''
// GENERATED by localino_builder — do not edit by hand.
// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars

abstract final class LocalinoKeys {
  /// Add
  static const action_add = 'action_add';

  /// Delete locale
  /// ⚠ missing in: cs_CZ
  static const action_delete_locale = 'action_delete_locale';

  /// (list)
  static const menu_tabs = 'menu_tabs';

  /// (map)
  static const onboard_card_1 = 'onboard_card_1';

  /// Version: {version} ({number})
  /// params: version, number
  static const version = 'version';
}
''';
    expect(generateLocalinoKeys(keys), expected);
  });

  test('deterministic across runs', () {
    expect(generateLocalinoKeys(keys), generateLocalinoKeys(keys));
  });

  test('generated source passes dart analyze clean', () async {
    final dir = await Directory.systemTemp.createTemp('localino_gen_');
    addTearDown(() => dir.delete(recursive: true));

    final file = File('${dir.path}/localino_keys.dart');
    await file.writeAsString(generateLocalinoKeys(keys));

    final result = await Process.run('dart', ['analyze', file.path]);
    expect(
      result.exitCode,
      0,
      reason: 'analyze output:\n${result.stdout}\n${result.stderr}',
    );
  });
}
