name: localino_builder
description: Builder to download and store json translations via Localino REST API.
homepage: https://localino.app
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  build: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
