name: localino_builder
description: Builder to download and store json translations via Localino REST API.
homepage: https://localino.app
version: 0.1.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ">=0.13.5 <1.0.0"

  build: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
