name: ci
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
#   path: ^1.8.0

  # https://pub.dev/packages/process_run
  process_run: ^0.13.1
